In [1]:
import numpy as np 
import gym 
import random 
import time 
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001 

In [8]:
rewards = []

#Q Learning algo
for episode in range(num_episodes):
    state = env.reset()
    
    done = False 
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate: 
            action = np.argmax(q_table[state, :])
        else: 
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        #update Q-table 
        q_table[state, action] = q_table[state, action]*(1-learning_rate) + \
            learning_rate*(reward + discount_rate* np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    # exploration decay  
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards.append(rewards_current_episode)
   
rewards_per_thousand_episodes = np.split(np.array(rewards), num_episodes/1000)
count = 1000

for r in rewards_per_thousand_episodes: 
    print(count, "; ", str(sum(r/1000)))
    count += 1000
    
print(q_table)


1000 ;  0.03400000000000002
2000 ;  0.21700000000000016
3000 ;  0.44000000000000034
4000 ;  0.5600000000000004
5000 ;  0.6240000000000004
6000 ;  0.6380000000000005
7000 ;  0.6770000000000005
8000 ;  0.6850000000000005
9000 ;  0.6720000000000005
10000 ;  0.7050000000000005
[[0.55302325 0.52843622 0.52618717 0.52447296]
 [0.30584972 0.25151467 0.22933831 0.51192986]
 [0.41258448 0.41899806 0.40244241 0.48994399]
 [0.32178861 0.33229425 0.27775502 0.46937593]
 [0.57417848 0.37143568 0.29673091 0.30878622]
 [0.         0.         0.         0.        ]
 [0.46534223 0.17676397 0.20501685 0.15308144]
 [0.         0.         0.         0.        ]
 [0.41751296 0.41526451 0.28035399 0.61119469]
 [0.384799   0.6552842  0.57771302 0.43469414]
 [0.59184491 0.34020576 0.43434481 0.32972295]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.59043261 0.5049833  0.76154063 0.60270951]
 [0.75223783 0.87072465 0.75081443 0.75769606]
 [0.         0.      

In [13]:
for episode in range(5):
    state = env.reset()
    print(state)
    done = False 
    print("********EPISODE", episode+1, "**********\n\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done: 
            clear_output(wait=True)
            env.render()
            if reward == 1: 
                print("Reached Goal!")
                time.sleep(3)
                
            else: 
                print("You fell through")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
Reached Goal!
